# run: conda env create --file environment.yml
name: jupyter-max2-proxy
channels:
  - conda-forge
dependencies:
  - jupyterlab=3
  - jupyterlab_server
  - jupyter-server-proxy>=3.1.0
  - jupyter_conda
  - pip
  - pip:
#      - xpra>=4.0.4
      - -r file:requirements.txt
      - netifaces
      - python-uinput
